### ISSUE TITLE
Add send route for base64 images

### ISSUE THREAD

**Issue by Achoobert** [digi-serve/ab_service_file_processor#36]
> receive encoded images and add them to the database

The relay server does not support passing images, encoding the files seems to have worked fine in the old version of the mobile app.

## Requirements
1. send base64
2. receive base64

### Tasks
- [x] Write Documentation
- [x] add route to add
- [x] Add file_processor methods
 - - [x] Upload base64
- [x] Update mobile app to support routesd

## Reference

Nathan's iwp branch
https://github.com/digi-serve/ab_service_api_sails/tree/nh/base64-file

old ops_portal version
https://github.com/appdevdesigns/appdev-opsportal/blob/6c0f33e5326f2245da51859cee6c8c7a9930d657/config/routes.js#L24

https://github.com/appdevdesigns/appdev-opsportal/blob/6c0f33e5326f2245da51859cee6c8c7a9930d657/api/controllers/OPImageUploadController.js#L386

https://github.com/appdevdesigns/appdev-opsportal/blob/6c0f33e5326f2245da51859cee6c8c7a9930d657/assets/opstools/UserProfile/controllers/UserProfile.js#L283
